version: '1'
services:
  dev:
    image: myothiha/ml-flask:a2.0
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: flask.Dockerfile
    volumes:
      - ./source_code:/root/source_code
      - ./.vscode-server:/root/.vscode-server
    command: python3 app.py