version: '3.9'

services:
  dev:
    image: myothiha/ml-flask:a2.0
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: flask.Dockerfile
    volumes:
      - ./source_code:/root/source_code
      - ./.vscode-server:/root/.vscode-server
    command: python3 app.py
  mlflow:
    image: akraradets/ait-ml-mlflow:2023
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 5000:5000